language: csharp
mono:
- latest
install:
- nuget restore
script:
- ./.ci.sh
env:
  secure: FfoBjfQdmRfyfyMnH6kdoeSmLk69L2EW4wMuSgJilstTUQ7dXlAf6JDbmptKxv7EzyNHuz5bAG8avZ2z4zFM1Upm9kUImyyM/AyvdLjfEakDoGUJNDoFW8LhVqhI/EqVXxgv00OzG9xqT8CseurZ5E3kswhvJL5LIoyjBuIl/1eBNSGnnfRZQbJhcxD0y7mTwF5sJahsbmDq0VWtSA9NyY7UE1Wf7MxCPw/89MA9ZUUFd/1MBt/l9sAiaO1ocNRAlEllQVcua+HceotXvV9XarInxiT75FCALm51qbPzPFE77RVn1Lz0AwUm1xq9ZVBX1PYzF3LVEgtBBUcVfyQ+jNpDmxlXSnKQc9qbFdPANi9LHjXS/9240GjmzeWvlcLUaN6a+GJNHmme98UAWAX/GAzc2Lxgu3VIE9DGN6uJRHJOuEyvKQgGHEbqYcnrITdD4QWupm9Szh32BObE327HRXNdlszra7Ei3DVgSnwGhvS1tEZgeyHli92hhmWw42to+CNjxB8+HTFGu3WAPMBwhPCJMlFtTxFCL4BmxD2wNwdswlHLOQPqyAkqcPpeZ46boybhfHkt2PJBlKqOPBlURwk77qJzc/6p+9Hv8arx2n7xMweDzyctGbQZNhe5HFrBBwXDKXAK2hjEcPMB5MIaIDbp7QjGgITZ4FKDfxqEgJU=
